### ISSUE TITLE
Keystore file download fail (Linux, Firefox 67.0)

### ISSUE THREAD

**Issue by vedun** [SilentNotaryEcosystem/Cil-core#23]
When i try to create new wallet, in some step i see next popup [window](https://postimg.cc/8sPJz91g), after i press "download keystore file" interface immediatly switch to Wallets page, download operation not starting.

**Comment by trueshura** [comment]
Hi.

Issue is confirmed, I informed support team.
But, since it's related to `Ubikiri` not Cil-core, i'll close this issue.
