### ISSUE TITLE
discrepancy on transaction number on CIL logs

### ISSUE THREAD

**Issue by fredblockchain** [SilentNotaryEcosystem/Cil-core#89]
Hi team!
Just wanted to point out some discrepancy between node's logs and ubikiri explorer.
In the logs of the node we can see that all the block have at least 1 transaction but in ubikiri explorer only a few ones have transactions.

Here is an example, block 612e38cb04490a84f5f14b74fc54f8da146af923094cec28ca1e1cdce9aa1def

In the logs
`Block 612e38cb04490a84f5f14b74fc54f8da146af923094cec28ca1e1cdce9aa1def. ConciliumId: 4. With 1 TXns and parents 1d2394fc8db7abe3f902c1fea23057b9196d9367b0cec51871cf88fc107797f0 was accepted`

Same block in the [explorer](https://explorer.ubikiri.com/#block/612e38cb04490a84f5f14b74fc54f8da146af923094cec28ca1e1cdce9aa1def)

Not a critical issue :), but good to check anyway

**Comment by trueshura** [comment]
What's wrong with it?

Do you mean 1TX that isn't displayed?

ср, 31 мая 2023 г. в 23:36, fredblockchain ***@***.***>:

**Comment by fredblockchain** [comment]
Hi,
Not 100% sure (I have no way to tell myself) but I would say that the correct info is that the block has no transaction, so the explorer is showing the correct info, whereas the node's log are showing incorrect info: it says "block with 1 transaction" where it should say "block with 0 transaction"

I suppose both places should show the same info...

Please find attached the screenshot of the explorer as I see it for the example of my first message, just in case you don't see it the same way:
![screenshot-2023-06-01_13-26](https://github.com/SilentNotaryEcosystem/Cil-core/assets/73721726/50fc2980-6da4-4b33-909f-7617e16c3c94)

Cheers

**Comment by trueshura** [comment]
every block should have a coinbase TX
"empty" blocks has empty coinbase
so explorer show this block as "empty"

чт, 1 июн. 2023 г. в 19:36, fredblockchain ***@***.***>:

**Comment by fredblockchain** [comment]
ok, so if I understand correctly the node's log include this one coinbase transaction within the count of block's transaction but the explorer does not, it excludes this coinbase from the transaction list shown to the user.
That's make sense,
I suppose there is no issue here and I should close this issue as "not planned", shouldn't I?
Fred

**Comment by trueshura** [comment]
Yes, exactly.

чт, 1 июн. 2023 г. в 20:52, fredblockchain ***@***.***>:
